# Generated by Django 3.1.7 on 2021-03-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updates',
            new_name='updated',
        ),
    ]
